manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 197f8997776c960b6d2d368909895735f859a4b4
      import: app/west.yml
  self:
    path: config
