manifest:
  remotes:
    - name: YkieWang
      url-base: https://github.com/YkieWang
    - name: inorichi
      url-base: https://github.com/inorichi
  projects:
    - name: zmk
      remote: YkieWang
      revision: e844eca2e9e3f56443b1e27d18c23144ca35b6ad
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: inorichi
      revision: 1d9c2c68ca76012e1b1e5f6ef02fa5eadc4ca399
  self:
    path: config
